LOAD DATA LOCAL INFILE "restaurant.dat"
INTO TABLE restaurant
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "owner.dat"
INTO TABLE owner
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "dish.dat"
INTO TABLE dish
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "customer.dat"
INTO TABLE customer
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "orders.dat"
INTO TABLE orders
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "orderdishes.dat"
INTO TABLE orderdishes
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE "rcomment.dat"
INTO TABLE rcomment
FIELDS TERMINATED BY ',';

