LOAD DATA LOCAL INFILE "restaurant_new_info.dat"
INTO TABLE UROB_Restaurant
FIELDS TERMINATED BY ","
LINES TERMINATED BY "\r\n";

LOAD DATA LOCAL INFILE "new_dish.dat"
INTO TABLE UROB_Dish
FIELDS TERMINATED BY ","
LINES TERMINATED BY "\r\n";